name: vna
description: A DICOM VNA
version: 0.1.0
#homepage: https://www.example.com
author: Jim Philbin <jfphilcin@google.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  converter:
    version: ^0.7.5
    path: C:/odw/sdk/converter
  core:
    version: ^0.7.6
    path: C:/odw/sdk/core
  io_extended:
    version: ^0.7.5
    path: C:/odw/sdk/io_extended


dev_dependencies:
  test: any
