name: vna
description: A DICOM Vendor Neutral Archive (VNA)
version: 0.1.0
#homepage: https://www.example.com
author: Jim Philbin <jfphilcin@google.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  json_annotation: ^2.0.0
  converter:
    version: ^0.7.0
    path: 'C:/odw/sdk/converter'
  core:
    version: ^0.7.0
    path: 'C:/odw/sdk/core'
  io_extended:
    version: ^0.7.0
    path: 'C:/odw/sdk/io_extended'


dev_dependencies:
  benchmark_harness: any
  grinder: ^0.8.0
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  test: any
