name: vna
description: A DICOM Study VNA
version: 0.1.0
#homepage: https://www.example.com
author: Jim Philbin <jfphilcin@google.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  convert:
    version: ^0.7.0
    path: C:/acr/odw/sdk/convert
  core:
    version: ^0.7.0
    path: C:/acr/odw/sdk/core
  io:
    version: ^0.7.0
    path: C:/acr/odw/sdk/io


dev_dependencies:
  test: ^0.12.0
